version: '3.5'

services:
  boldreports:
   container_name: boldreports
   image: syncfusion/boldreports
   restart: always
   ports:
     - 80:80
   environment:
     # Set the Application base URL or the machine IP of external DNS to access the site. For example: https://example.com or http://172.174.25.9 or http://host.docker.internal
     - APP_URL=<APP_URL>
     # Set the unlock key value from the unlock_key.lic file, which can be obtained from the accounts page(https://www.boldreports.com/account).
     - BOLD_SERVICES_UNLOCK_KEY=<BOLD_SERVICES_UNLOCK_KEY>
     # Preconfigured PostgreSQL database details that are deployed along with this deployment.
     - BOLD_SERVICES_DB_TYPE=postgresql
     - BOLD_SERVICES_DB_HOST=pgdb
     - BOLD_SERVICES_POSTGRESQL_MAINTENANCE_DB=postgres
     - BOLD_SERVICES_DB_USER=postgres
     - BOLD_SERVICES_DB_PASSWORD=Admin@123
     # Set the site admin user Mail ID.
     - BOLD_SERVICES_USER_EMAIL=demo@boldreports.com
     # Set the site admin user password.
     - BOLD_SERVICES_USER_PASSWORD=Admin@123
    # Uncomment the line below, if you want to use the client libraries.
   # - OPTIONAL_LIBS=mysql,oracle,postgresql
   networks:
     - boldreports
   volumes:
     - boldreports_data:/application/app_data
    
  pgdb:
    image: postgres
    restart: always
    environment:
    # Set the password for the PostgreSQL database that will be deployed along with this Bold Reports deployment.
      POSTGRES_PASSWORD: Admin@123
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - boldreports

networks:
  boldreports:
  
volumes:
  boldreports_data:
  db_data: