version: '3.5'
services:
  boldreports:
   image: public.ecr.aws/x7k6q2v7/boldreports-single-docker:5.4.21
   restart: always
   ports:
     - 80:80
   environment:
     # Set the Application base URL or the machine IP of external DNS to access the site. For example: https://example.com or http://172.174.25.9 or http://host.docker.internal
     - APP_URL=<APP_URL>
     # Uncomment the line below, if you want to use the client libraries.
    #  - OPTIONAL_LIBS=mysql,oracle,postgresql
   networks:
     - boldreports
   volumes:
     - boldreports_data:/application/app_data
    
  pgdb:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: Admin@123
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - boldreports
networks:
  boldreports:
  
volumes:
  boldreports_data:    
  db_data: